name: "Test typescript-action"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: ./
      with: 
        milliseconds: 1000
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.ref }}
        required_contexts: "[]"
